### ISSUE TITLE
[BUG][iOS] Japanese text Not Properly Rendered in Clarity Session Recordings (SwiftUI)

### ISSUE THREAD

**Issue by shingohry** [microsoft/clarity-apps#125]
**Describe the Bug**
In our iOS app using SwiftUI, Japanese Text render correctly on device but appear missing in Microsoft Clarity session recordings.

**Repro Steps**
1. Create an iOS app using SwiftUI.
1. Add SwiftUI.Text to display Japanese text
1. Integrate Clarity SDK and record a session.
1. View the recording in the Clarity portal.

I have prepared a repository of sample apps that you can use to reproduce the problem:
- https://github.com/shingohry/ClarityTest/blob/main/ClarityTest/ContentView.swift#L18-L19

**Expected Behavior**
Japanese text should appear exactly as rendered in the app.

**Screenshots**
| Device screenshot | Clarity Recordings screenshot |
|-|-|
| <img src="https://github.com/user-attachments/assets/dd384015-fc24-4962-ba5c-a2d902bacc16" width="480"> | <img src="https://github.com/user-attachments/assets/ad951083-b1a1-4be7-a0b3-2e3f65f05ffe" width="480"> |

**Platform/Framework Info**

- Device: [iPad Air 13-inch (M2)]
- OS: [iOS 18.4]
- Application Framework [Native SwiftUI-based]
- Clarity Version: [3.0.7]
- Xcode Version: [16.4]

**Additional Context**
The value of Settings > Masking in the admin panel is set to "Relaxed".

**Comment by sun-junota** [comment]
Additional research on this issue.

- The problem is reproducible with both SwiftUI and UIKit implementations.
- Upon investigating in English, Chinese, Japanese, Russian, Egyptian, and Korean, the issue is only reproducible in Chinese and Japanese (it does not reproduce in English, Russian, Egyptian, or Korean).

![Image](https://github.com/user-attachments/assets/84847e4b-e99a-49fb-b618-04017c560d35)

**Comment by shingohry** [comment]
@ibradwan Thanks for the update! Does updating to the latest SDK version fix the issue?

**Comment by ibradwan** [comment]
@shingohry you don't need to upgrade the SDK. It should be fixed automatically.

**Comment by shingohry** [comment]
@ibradwan Thank you for your prompt response and the update.

I have updated the Clarity SDK to the latest version (3.0.10) and re-tested the issue using the same sample app and settings. Unfortunately, the issue with Japanese text not displaying properly in session recordings still persists.

Additionally, I have also tested with some older versions of the SDK (from 3.0.7 to 3.0.9), and the same issue was observed in those versions as well.

Could you please clarify:
- What specific fixes were applied for this issue, and from which version?
- Are there any additional settings or steps required on our end?
- Would you need any logs or further information to investigate?

Thank you for your support. Please let me know if there’s anything else I can do to help resolve this issue.

**Comment by ibradwan** [comment]
@shingohry,

That's weird. Please enable the SDK logs (by setting the log level to verbose) and thne share the full log to `clarity-apps-support@microsoft.com`.

**Comment by shingohry** [comment]
@ibradwan I have confirmed that the issue has been resolved. Thank you very much for your support.
