### ISSUE TITLE
Android sdk doesn't support AndroidComposeView

### ISSUE THREAD

**Issue by mvij** [microsoft/clarity-apps#26]
Microsoft clarity sdk version : 2.0.0
Device : Oneplus 7pro
Android : 12

The screen recording taken on the device is completely black, where screen touches and taps are getting recorded but nothing else is visible
![Screenshot 2023-12-13 at 15-54-37 Microsoft Clarity - Free Heatmaps   Session Recordings](https://github.com/microsoft/clarity-apps/assets/9973014/1e9336da-a8fc-4362-8233-bd77209208e4)

Heatmap shows up like this

![Screenshot 2023-12-13 at 16-21-47 Microsoft Clarity - Free Heatmaps   Session Recordings](https://github.com/microsoft/clarity-apps/assets/9973014/80e6b065-b7c1-4692-acd8-50c0d7810e78)

Is android compose view not supported?

**Comment by ibradwan** [comment]
Hi @mvij,

Thanks for sharing the feedback, we currently have limited support for JetPack compose. We do have plans to enhance the support so please stay tuned.

**Comment by axitasavani** [comment]
Hi, @mvij  and @ibradwan  I have faced the same issue with my app in that some of the components are not showing up in recordings. and some of the cut the UI.
Could you please solution while here...

**Comment by ibradwan** [comment]
The Jetpack compose package is expected to be published soon, so please stay tuned.

**Comment by TohidMahmamoudvand** [comment]
I have the same issue, When will this issue be solved?
@ibradwan

**Comment by nikhilbiju67** [comment]
Any update on the support of jetpack compose?

**Comment by IvanLarenas** [comment]
@ibradwan is the support for jetpack compose out already?

**Comment by ibradwan** [comment]
We've just released our first compose package (clarity-compose) 😀 Please give it a shot and let us know your feedback.

**Comment by nikhilbiju67** [comment]
Hey i am using implementation("com.microsoft.clarity:clarity-compose:2.5.0")
but it still compose views are not shown in dashboard
@ibradwan

**Comment by leinardi** [comment]
@ibradwan is there some documentation or a sample project that shows how to use clarity with compose?

**Comment by ibradwan** [comment]
Yes, please check this [link](https://learn.microsoft.com/en-us/clarity/mobile-sdk/clarity-compose-sdk).

**Comment by souravLevel** [comment]
@ibradwan Still facing the same issue mentioned above with jetpack compose. It would be great if you could give us an update regarding the same. Thank you in advance
![Screenshot 2024-08-03 005504](https://github.com/user-attachments/assets/15f762b6-4510-4fe2-acbe-3d03b2b96ae9)

**Comment by SaadeldinBadr** [comment]
Hello @souravLevel 
Which version of compose are you using?

**Comment by dennymoradiya** [comment]
is there any final solution?

**Comment by leinardi** [comment]
I'm also facing the very same issue. I'm currently using Compose 1.7.0, and I understand that the latest officially supported version is 1.6.8, so this might be related.

![image](https://github.com/user-attachments/assets/ca03ae9e-f9d9-482c-b176-9ba67285b67f)

As you know, Compose evolves rapidly, and for us to be able to fully adopt Clarity, it's crucial that this library stays up to date with the latest versions. I’d also like to suggest considering support for non-stable versions of Compose (alpha and beta), as many important fixes and new features are introduced in these early releases. While I understand the caution against using alpha versions in production, Compose feels like one of the rare exceptions where the benefits—like fixing specific bugs—often outweigh the risks.

**Comment by Woren** [comment]
I suggest to create new issue with request for supporting alpha/beta versions or trying to "decouple" clarity/compose that there are not such requirements for updating clarity with new version of compose. If that is even possible.

**Comment by leinardi** [comment]
@Woren oh I didn't notice that was already closed, I'll open new ones for my issues, thanks.

**Comment by SaadeldinBadr** [comment]
Hello everyone,

As mentioned here  [Supported Jetpack Compose Versions](https://learn.microsoft.com/en-us/clarity/mobile-sdk/clarity-compose-sdk#supported-jetpack-compose-versions), `clarity-compose:2.5.0` only supports stable compose releases from `1.0.0` to `1.6.8`. Please check your compose version to ensure compatibility. In future Clarity releases, we plan to support upcoming compose versions, including alpha & beta releases, as compose evolves rapidly.

**Comment by dennymoradiya** [comment]
I am using 2.5.0, but still facing this problem

**Comment by SaadeldinBadr** [comment]
Hello Everyone,
We've just released `clarity-compose:3.1.0` , which supports latest jetpack compose `1.7.*`.
Please give it a try and let us know if you faced any issues.

**Comment by dennymoradiya** [comment]
@SaadeldinBadr, sure.

Thanks for the update.

**Comment by Sourav19o7** [comment]
@SaadeldinBadr thanks for the update. We'll let you know if there are any issues

**Comment by dennymoradiya** [comment]
@SaadeldinBadr 

Still Same 

` implementation 'com.microsoft.clarity:clarity:3.1.2'`


Recording for you reference --> [](https://clarity.microsoft.com/shared/recording/d08f7018-7867-444d-9dc8-5147651c381b)

**Comment by SaadeldinBadr** [comment]
@dennymoradiya you should use `implementation 'com.microsoft.clarity:clarity-compose:3.1.2'`, give it a try and let me know if it works.
